# http://www.apache.org/licenses
# Use the official Nginx image
FROM nginx:alpine

# Copy the index.html to the Nginx web server directory
COPY /web/index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80
